# Docker Compose configuration for local development
# This version doesn't require HTTPS and runs without Traefik
# Usage: docker compose -f docker-compose.dev.yml up

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-dating}
      POSTGRES_USER: ${POSTGRES_USER:-dating}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dating}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-dating} -d ${POSTGRES_DB:-dating}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-dating}:${POSTGRES_PASSWORD:-dating}@db:5432/${POSTGRES_DB:-dating}
      WEBAPP_URL: ${WEBAPP_URL:-http://localhost:8080}
    restart: unless-stopped

  webapp:
    image: nginx:1.25-alpine
    ports:
      - "${WEBAPP_PORT:-8080}:80"
    volumes:
      - ./webapp:/usr/share/nginx/html:ro
    restart: unless-stopped

volumes:
  postgres_data_dev:
