# Production Docker Compose configuration with HTTPS support
#
# This configuration includes Traefik as a reverse proxy with automatic
# Let's Encrypt SSL certificate generation.
#
# Requirements for HTTPS:
# - Set DOMAIN to your public domain name
# - Set ACME_EMAIL to receive certificate expiration notifications
# - Set WEBAPP_URL to https://your-domain.com
# - Ensure DNS points to your server IP
# - Ensure ports 80 and 443 are open in firewall
#
# For local development without HTTPS, use docker-compose.dev.yml instead:
#   docker compose -f docker-compose.dev.yml up

services:
  traefik:
    image: traefik:v2.11
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL:-admin@example.com}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.caserver=${ACME_CA_SERVER:-https://acme-v02.api.letsencrypt.org/directory}"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_certs:/letsencrypt
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-dating}
      POSTGRES_USER: ${POSTGRES_USER:-dating}
      # IMPORTANT: Use only alphanumeric characters (A-Z, a-z, 0-9) for POSTGRES_PASSWORD
      # Special characters in passwords require URL encoding in connection strings and may cause authentication issues
      # If you change the password after initial deployment, you must reset the database volume:
      #   docker compose down -v && docker compose up
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-dating}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-dating} -d ${POSTGRES_DB:-dating}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      # Database URL is constructed from individual POSTGRES_* variables
      # This works correctly only if POSTGRES_PASSWORD contains URL-safe characters
      BOT_DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-dating}:${POSTGRES_PASSWORD:-dating}@db:5432/${POSTGRES_DB:-dating}
      WEBAPP_URL: ${WEBAPP_URL:-https://localhost}
    restart: unless-stopped

  webapp:
    image: nginx:1.25-alpine
    volumes:
      - ./webapp:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webapp.rule=Host(`${DOMAIN:-localhost}`)"
      - "traefik.http.routers.webapp.entrypoints=websecure"
      - "traefik.http.routers.webapp.tls.certresolver=letsencrypt"
      - "traefik.http.services.webapp.loadbalancer.server.port=80"
    restart: unless-stopped

volumes:
  postgres_data:
  traefik_certs:
