name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare SSH key
        run: |
          mkdir -p "$GITHUB_WORKSPACE/.ssh"
          echo "${{ secrets.DEPLOY_SSH_KEY_B64 }}" | base64 -d > "$GITHUB_WORKSPACE/.ssh/ci_key"
          chmod 600 "$GITHUB_WORKSPACE/.ssh/ci_key"

      - name: Test SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key_path: ${{ github.workspace }}/.ssh/ci_key
          script: 'whoami'

      - name: Upload application bundle
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key_path: ${{ github.workspace }}/.ssh/ci_key
          source: "."
          target: ${{ secrets.DEPLOY_PATH }}
          overwrite: true

      - name: Write .env and compose up
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key_path: ${{ github.workspace }}/.ssh/ci_key
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            cat > .env <<'EOF'
            ${{ secrets.ENV_FILE }}
            EOF
            docker compose up -d --build
            docker compose ps
