name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]  # можно убрать, если хочешь только ручной запуск

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          # passphrase: ${{ secrets.DEPLOY_SSH_KEY_PASSPHRASE }}
          script: 'echo "SSH OK on $(hostname) as $(whoami)"'

      - name: Upload application bundle
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          # passphrase: ${{ secrets.DEPLOY_SSH_KEY_PASSPHRASE }}
          source: "."
          target: ${{ secrets.DEPLOY_PATH }}
          overwrite: true

      - name: Write .env on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          # passphrase: ${{ secrets.DEPLOY_SSH_KEY_PASSPHRASE }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            cat > .env <<'EOF'
            ${{ secrets.ENV_FILE }}
            EOF
            echo ".env written ($(wc -l < .env) lines)"

      - name: Compose up
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            sudo docker compose up -d --build
            sudo docker compose ps
