name: WebApp CI

on:
  push:
    branches: [main, develop, "copilot/**"]
    paths:
      - "webapp/**"
      - ".github/workflows/webapp-ci.yml"
  pull_request:
    branches: [main, develop]
    paths:
      - "webapp/**"
      - ".github/workflows/webapp-ci.yml"

concurrency:
  group: webapp-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-build:
    name: Lint, Type Check & Build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: webapp

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: webapp/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Check code formatting
        run: npm run format:check

      - name: Run TypeScript type check
        run: npm run type-check

      - name: Build production bundle
        run: npm run build
        env:
          NEXT_TELEMETRY_DISABLED: 1
          NEXT_PUBLIC_API_URL: "http://localhost:9999"
          API_URL: "http://localhost:9999"

      - name: Check build output
        run: |
          if [ ! -d ".next" ]; then
            echo "Build failed: .next directory not found"
            exit 1
          fi
          echo "✅ Build completed successfully"

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('webapp/package-lock.json') }}

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright smoke tests (SSR)
        run: npm run test:ci
        env:
          CI: "1"
          NEXT_TELEMETRY_DISABLED: "1"
          NEXT_PUBLIC_API_URL: "http://localhost:9999"
          API_URL: "http://localhost:9999"

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: webapp/playwright-report
          retention-days: 7

      - name: Upload Playwright traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: webapp/test-results
          retention-days: 7
